
export const PIANO = {
  // 0: {
  //   9: {filePath: "./assets/sound_files/piano/C1.wav", idx: 0},
  //   8: {filePath: "./assets/sound_files/piano/D1.wav", idx: 2},
  //   7: {filePath: "./assets/sound_files/piano/E1.wav", idx: 4},
  //   6: {filePath: "./assets/sound_files/piano/F1.wav", idx: 5},
  //   5: {filePath: "./assets/sound_files/piano/G1.wav", idx: 7},
  //   4: {filePath: "./assets/sound_files/piano/A1.wav", idx: 9},
  //   3: {filePath: "./assets/sound_files/piano/B1.wav", idx: 11},
  //   2: {filePath: "./assets/sound_files/piano/C2.wav", idx: 12},
  //   1: {filePath: "./assets/sound_files/piano/D2.wav", idx: 14},
  //   0: {filePath: "./assets/sound_files/piano/E2.wav", idx: 16},
  // },
  // 1: {
  //   9: { filePath: "./assets/sound_files/piano/C2.wav", idx: 12 },
  //   8: { filePath: "./assets/sound_files/piano/D2.wav", idx: 14 },
  //   7: { filePath: "./assets/sound_files/piano/E2.wav", idx: 16 },
  //   6: { filePath: "./assets/sound_files/piano/F2.wav", idx: 17 },
  //   5: { filePath: "./assets/sound_files/piano/G2.wav", idx: 19 },
  //   4: { filePath: "./assets/sound_files/piano/A2.wav", idx: 21 },
  //   3: { filePath: "./assets/sound_files/piano/B2.wav", idx: 23 },
  //   2: { filePath: "./assets/sound_files/piano/C3.wav", idx: 24 },
  //   1: { filePath: "./assets/sound_files/piano/D3.wav", idx: 26 },
  //   0: { filePath: "./assets/sound_files/piano/E3.wav", idx: 28 },
  // },
  // 2: {
  //   9: { filePath: "./assets/sound_files/piano/C3.wav", idx: 24 },
  //   8: { filePath: "./assets/sound_files/piano/D3.wav", idx: 26 },
  //   7: { filePath: "./assets/sound_files/piano/E3.wav", idx: 28 },
  //   6: { filePath: "./assets/sound_files/piano/F3.wav", idx: 29 },
  //   5: { filePath: "./assets/sound_files/piano/G3.wav", idx: 31 },
  //   4: { filePath: "./assets/sound_files/piano/A3.wav", idx: 33 },
  //   3: { filePath: "./assets/sound_files/piano/B3.wav", idx: 35 },
  //   2: { filePath: "./assets/sound_files/piano/C4.wav", idx: 36 },
  //   1: { filePath: "./assets/sound_files/piano/D4.wav", idx: 38 },
  //   0: { filePath: "./assets/sound_files/piano/E4.wav", idx: 40 },
  // }, 
  // 3: {
  //   9: { filePath: "./assets/sound_files/piano/C4.wav", idx: 36 },
  //   8: { filePath: "./assets/sound_files/piano/D4.wav", idx: 38 },
  //   7: { filePath: "./assets/sound_files/piano/E4.wav", idx: 40 },
  //   6: { filePath: "./assets/sound_files/piano/F4.wav", idx: 41 },
  //   5: { filePath: "./assets/sound_files/piano/G4.wav", idx: 43 },
  //   4: { filePath: "./assets/sound_files/piano/A4.wav", idx: 45 },
  //   3: { filePath: "./assets/sound_files/piano/B4.wav", idx: 47 },
  //   2: { filePath: "./assets/sound_files/piano/C5.wav", idx: 48 },
  //   1: { filePath: "./assets/sound_files/piano/D5.wav", idx: 50 },
  //   0: { filePath: "./assets/sound_files/piano/E5.wav", idx: 52 },
  // },
  4: {
    9: { filePath: "./assets/sound_files/piano/C5.wav", idx: 1 },
    8: { filePath: "./assets/sound_files/piano/D5.wav", idx: 3 },
    7: { filePath: "./assets/sound_files/piano/E5.wav", idx: 5 },
    6: { filePath: "./assets/sound_files/piano/F5.wav", idx: 6 },
    5: { filePath: "./assets/sound_files/piano/G5.wav", idx: 8 },
    4: { filePath: "./assets/sound_files/piano/A5.wav", idx: 10 },
    3: { filePath: "./assets/sound_files/piano/B5.wav", idx: 12 },
    2: { filePath: "./assets/sound_files/piano/C6.wav", idx: 13 },
    1: { filePath: "./assets/sound_files/piano/D6.wav", idx: 15 },
    0: { filePath: "./assets/sound_files/piano/E6.wav", idx: 17 },
  }, 
  // 5: {
  //   9: { filePath: "./assets/sound_files/piano/C6.wav", idx: 60 },
  //   8: { filePath: "./assets/sound_files/piano/D6.wav", idx: 62 },
  //   7: { filePath: "./assets/sound_files/piano/E6.wav", idx: 64 },
  //   6: { filePath: "./assets/sound_files/piano/F6.wav", idx: 65 },
  //   5: { filePath: "./assets/sound_files/piano/G6.wav", idx: 67 },
  //   4: { filePath: "./assets/sound_files/piano/A6.wav", idx: 69 },
  //   3: { filePath: "./assets/sound_files/piano/B6.wav", idx: 71 },
  //   2: { filePath: "./assets/sound_files/piano/C7.wav", idx: 72 },
  //   1: { filePath: "./assets/sound_files/piano/D7.wav", idx: 74 },
  //   0: { filePath: "./assets/sound_files/piano/E7.wav", idx: 76 },
  // }
}

export const PIANO_PATHS = {
  // 0: "./assets/sound_files/piano/C1.wav",
  // 1: "./assets/sound_files/piano/DB1.wav",
  // 2: "./assets/sound_files/piano/D1.wav",
  // 3: "./assets/sound_files/piano/EB1.wav",
  // 4: "./assets/sound_files/piano/E1.wav",
  // 5: "./assets/sound_files/piano/F1.wav",
  // 6: "./assets/sound_files/piano/GB1.wav",
  // 7: "./assets/sound_files/piano/G1.wav",
  // 8: "./assets/sound_files/piano/AB1.wav",
  // 9: "./assets/sound_files/piano/A1.wav",
  // 10: "./assets/sound_files/piano/BB1.wav",
  // 11: "./assets/sound_files/piano/B1.wav",

  // 12: "./assets/sound_files/piano/C2.wav",
  // 13: "./assets/sound_files/piano/DB2.wav",
  // 14: "./assets/sound_files/piano/D2.wav",
  // 15: "./assets/sound_files/piano/EB2.wav",
  // 16: "./assets/sound_files/piano/E2.wav",
  // 17: "./assets/sound_files/piano/F2.wav",
  // 18: "./assets/sound_files/piano/GB2.wav",
  // 19: "./assets/sound_files/piano/G2.wav",
  // 20: "./assets/sound_files/piano/AB2.wav",
  // 21: "./assets/sound_files/piano/A2.wav",
  // 22: "./assets/sound_files/piano/BB2.wav",
  // 23: "./assets/sound_files/piano/B2.wav",

  // 24: "./assets/sound_files/piano/C3.wav",
  // 25: "./assets/sound_files/piano/DB3.wav",
  // 26: "./assets/sound_files/piano/D3.wav",
  // 27: "./assets/sound_files/piano/EB3.wav",
  // 28: "./assets/sound_files/piano/E3.wav",
  // 29: "./assets/sound_files/piano/F3.wav",
  // 30: "./assets/sound_files/piano/GB3.wav",
  // 31: "./assets/sound_files/piano/G3.wav",
  // 32: "./assets/sound_files/piano/AB3.wav",
  // 33: "./assets/sound_files/piano/A3.wav",
  // 34: "./assets/sound_files/piano/BB3.wav",
  // 35: "./assets/sound_files/piano/B3.wav",

  // 36: "./assets/sound_files/piano/C4.wav",
  // 37: "./assets/sound_files/piano/DB4.wav",
  // 38: "./assets/sound_files/piano/D4.wav",
  // 39: "./assets/sound_files/piano/EB4.wav",
  // 40: "./assets/sound_files/piano/E4.wav",
  // 41: "./assets/sound_files/piano/F4.wav",
  // 42: "./assets/sound_files/piano/GB4.wav",
  // 43: "./assets/sound_files/piano/G4.wav",
  // 44: "./assets/sound_files/piano/AB4.wav",
  // 45: "./assets/sound_files/piano/A4.wav",
  // 46: "./assets/sound_files/piano/BB4.wav",
  0: "./assets/sound_files/piano/B4.wav",

  1: "./assets/sound_files/piano/C5.wav",
  2: "./assets/sound_files/piano/DB5.wav",
  3: "./assets/sound_files/piano/D5.wav",
  4: "./assets/sound_files/piano/EB5.wav",
  5: "./assets/sound_files/piano/E5.wav",
  6: "./assets/sound_files/piano/F5.wav",
  7: "./assets/sound_files/piano/GB5.wav",
  8: "./assets/sound_files/piano/G5.wav",
  9: "./assets/sound_files/piano/AB5.wav",
  10: "./assets/sound_files/piano/A5.wav",
  11: "./assets/sound_files/piano/BB5.wav",
  12: "./assets/sound_files/piano/B5.wav",

  13: "./assets/sound_files/piano/C6.wav",
  14: "./assets/sound_files/piano/DB6.wav",
  15: "./assets/sound_files/piano/D6.wav",
  16: "./assets/sound_files/piano/EB6.wav",
  17: "./assets/sound_files/piano/E6.wav",
  18: "./assets/sound_files/piano/F6.wav",
  // 66: "./assets/sound_files/piano/GB6.wav",
  // 67: "./assets/sound_files/piano/G6.wav",
  // 68: "./assets/sound_files/piano/AB6.wav",
  // 69: "./assets/sound_files/piano/A6.wav",
  // 70: "./assets/sound_files/piano/BB6.wav",
  // 71: "./assets/sound_files/piano/B6.wav",

  // 72: "./assets/sound_files/piano/C7.wav",
  // 73: "./assets/sound_files/piano/DB7.wav",
  // 74: "./assets/sound_files/piano/D7.wav",
  // 75: "./assets/sound_files/piano/EB7.wav",
  // 76: "./assets/sound_files/piano/E7.wav",
  // 77: "./assets/sound_files/piano/F7.wav"
}



